export const dataList = {
  msg_notify: "(to send a notification)",
  list_of_emails: "List of emails",
  add: "Add",
  save_for_settings: "SAVE",
  save: "Save",
  set_questions: "Set questions",
  download: "Download",
  back: "Back",
  note: "Note",
  name: "Name",
  comments: "comments",
  lawschoolname: "lawschoolname",
  add_note: "Add note",
  no_of_reported_error: "# of Reported error(s)",
  item_code: "Item code",
  item_tag_code: "Item tag code",
  item: "Item",
  item_tags: "Item tags",
  last_reported_date: "Last reported date",
  item_errors: "Item errors",
  add_item_tag: "Add item tag",
  edit_item_tag: "Edit item tag",
  item_tag_information: "Item tag information",
  tag_code: "Tag code",
  tag_name: "Tag name",
  tag_category: "Tag category",
  description_content: "Description / content",
  active: "Active",
  in_active: "Inactive",
  delete: "Delete",
  show_all: "Show all",
  last_modified_date: "Last modified date",
  add_item_bank: "Add item bank",
  question: "Stimulus",
  status: "Status",
  select_status: "Select status",
  add_video: "Add video",
  edit_video: "Edit video",
  video_order: "Display order",
  display_order: "Display order",
  reference: "Reference",
  add_Reference: "Add reference",
  description: "Description",
  add_description: "Add description",
  source: "Source",
  add_source: "Add source",
  acknowledgements: "Acknowledgements",
  add_acknowledgements: "Add acknowledgements",
  scoring_type: "Scoring type",
  select_scoring_type: "Select scoring type",
  type: "Type",
  tag: "Tag",
  tags: "Tags",
  action: "Action",
  details: "Deatails",
  mcq: "MCQ",
  feature: "Feature",
  content_type: "Content type",
  question_type: "Question type",
  subject: "Subject / topic",
  formatting: "Formatting",
  font_size: "Font size",
  label_type: "Label type",
  style: "Style",
  validation: "Validation",
  check_answer_attempts: "Check answer attempts",
  select_correct_answers: "Select correct answers",
  minimun_score_if_attempted: "Minimun score if attempted",
  yes: "Yes",
  no: "No",
  valid_response: "Valid response",
  score: "Score",
  value: "Value",
  enable_auto_score: "Enable auto score",
  meta_data: "MetaData",
  distractor_rationale: "Distractor rationale",
  sample_answer: "Sample answer",
  rubic_reference: "Rubic reference",
  item_bank: "Item bank",
  code: "Code",
  title: "Title",
  school_code: "School code",
  enter_school_code: "Enter school code",
  school_name: "School name",
  enter_school_name: "Enter school name",
  phone_number: "Phone number",
  enter_phone_number: "Enter phone number",
  email: "Email",
  enter_email: "Enter email",
  law_schools_information: "Law school information",
  law_school_enquiry: "Law school enquiries",
  video_link: "Video link",
  enter_website_link: "Enter website link",
  category: "Category",
  select_category_of_school: "Select category of school",
  address: "Address",
  enter_school_address: "Enter school address",
  enter_person_name: "Enter person name",
  enter_person_email: "Enter person email",
  user_name: "User name",
  user_name_email: "User name / Email",
  enter_user_name: "Enter user name",
  please_wait: "Loading... please wait...",
  password: "Password",
  enter_user_password: "Enter user password",
  date: "Date",
  message: "Message",
  messages: "Messages",
  published: "Published",
  law_msg_publish: "Publish",
  draft: "Draft",
  unpublished: "Unpublished",
  message_subject: "Subject",
  write_your_message: "Write your message",
  message_published_to: "To whom",
  message_publish: "Publish now",
  lawschool_compose_to: "Send now",
  lawschool_msg_to: "To",
  created_by: "Created by",
  please_enter_message: "Please enter message",
  law_school_name: "Law school name",
  law_school: "Law school",
  total_law_schools: "Total law schools",
  new_law_school_quarter: "New law school quarter",
  new_onboard_request: "New onboard request",
  students: "Students",
  stud_reset_password: "Reset password link",
  total_students: "Total students",
  new_students_quarter: "New students quarter",
  item_banks: "Item banks",
  items_pending_review: "Items pending review",
  items_published: "Items published",
  reported_errors: "Reported errors",
  overview: "OVERVIEW",
  settings: "Settings",
  general_settings: "Basic information",
  setting_change_password: "Please change your password here",
  setting_time: "Please set the basic information",
  setting_change_head: "Change password",
  msg_center_notification: "Message center notification",
  standard_qa_time:
    "Average student answer time for each question during exam(seconds)",
  nat_avg_performance: "National average performance",
  link_to_expire: "Student invitation link expiration(hours)",
  settings_user_info: "User information",
  standard_question_time: "Standard question answer time",
  national_avg_performance: "National average performance",
  invitation_link_to_expire: "Invitation link to expire in hours",
  user_information: "User information",
  admin: "Admin",
  role: "Role",
  controller: "Controller",
  change_pwd: "Change your password",
  current_pwd: "Current password",
  enter_current_pwd: "Enter current password",
  new_pwd: "New password",
  enter_new_pwd: "Enter new password",
  confirm_pwd: "Confirm password",
  re_enter_pwd: "Re-enter password",
  profile_active: "Active",
  access_information: "Access information",
  student_name: "Student name",
  invite_students: "Invite students",
  invite: "Invite",
  student_code: "Student code",
  enter_student_code: "Enter student code",
  barbri_id: "Barbri ID",
  enter_barbri_id: "Enter barbri ID",
  student_orgnisation: "Student oragnisation id",
  enter_orgnisation: "Enter student oragnisation id",
  bar_exam_batch: "Bar exam batch",
  barbri_reference_no: "Barbri reference no",
  exam_name: "Exam name",
  exam_date: "Exam date",
  no_of_ques: "No. of questions",
  correct_answers: "Correct answers",
  upload: "Upload",
  exams: "Exams",
  questions: "Questions",
  student_law_school_id: "Student law school id",
  enter_lawschool_id: "Enter student law school id",
  enter_first_name: "Enter first name",
  last_name: "Last name",
  enter_last_name: "Enter last name",
  middle_name: "Middle name",
  enter_middle_name: "Enter middle initial",
  student_law_school: "Student law school",
  student_school_gpa: "student school GPA",
  student_last: "Student LSAT",
  enter_student_last: "Enter student LSAT",
  study_information: "Study information",
  student_exp_bar_exam: "Student expected bar exam taken",
  student_full_time: "Student full time",
  student_transfer: "Student transfer",
  profile_information: "Profile information",
  student_active: "Student active",
  student_phone: "Student phone",
  student_user_name: "Student user name",
  student_pwd: "Student password",
  select_law_school: "Select law school",
  expected_bar_exam_state: "Expected bar exam state",
  enter_expected_bar_exam_state: "Expected bar exam state",
  expected_bar_exam_date: "Expected bar exam date",
  enter_expected_bar_exam_date: "Expected bar exam date",
  selecte_bar_exam_date: "Select expected bar exam date",
  no_of_bar_exam: "Number Of previous bar exam taken",
  enter_no_of_bar_exam: "Enter number of previous bar exam taken",
  law_school_GPA: "Law school GPA",
  enter_law_school_GPA: "Enter law school GPA",
  deleted: "Deleted",
  Overall_search: "search",
  choose_file_to_select: "Choose file to select",
  get_help: "Get help",
  popular_search: "Popular search",
  please_Select: "Please select",
  viewer: "Viewer",
  operator: "Operator",
  proof_reader: "Proof readers",
  select_role: "Select role",
  mobile_number: "Mobile number",
  video_title: "Video title",
  video_title_info: "Video information",
  video_info: "Please enter video information",
  video_file_name: "Video file name",
  video_category: "Subject",
  video_library: "Video library",
  select_subject: "Select subject",
  civil_procedure: "Civil procedure",
  constitution_law: "Constitutional law",
  contracts: "Contracts",
  criminal_law: "Criminal law",
  evidence: "Evidence",
  real_property: "Real property",
  torts: "Torts",
  new: "New",
  archive: "Archive",
  select_all: "Select all",
  mark_as_read: "Mark as read",
  avg_score: "Average score",
  no_of_answered_question: "No of answered question",
  subject_over_time: "Subject over time",
  monthly_progress: "Monthly progress",
  progress_all_subjects: "Progress - all subjects",
  overall_score: "Overall score",
  monthly: "Monthly",
  weekly: "Weekly",
  batch: "Batch",
  all_batch: "All batch",
  set_password: "Set password",
  default_date: "Default date",
  Def_dates_for_perf_stats: "Default dates for performance stats",
  today: "Today",
  past_month: "Past month",
  past_year: "Past year",
  custom: "Custom",
  bar_exams_batches: "Bar exams - batches",
  clear_all_selection: "Clear all selection",
  download_report: "Download report",
  users: "Users",
  user_edit: "Edit user",
  user_add: "Add user",
  user_firstname: "First name",
  user_lastname: "Last name",
  user_heading: "Access information",
  user_title: "Basic information",
  lawschool_msg_title: "Compose new message",
  law_compose: "Compose",
  lawschool_msg_heading: "Prepare your message to students below",
  user_type: "User type",
  add_lawschool: "Add law school",
  edit_lawschool: "Edit law school",
  stud_setting_time:
    "To complete the MBE, students must work at a pace of 1 minute 48 seconds per question. To accommodate disabilities, some students are given extra time to complete the exam. If you will receive extra time on the exam, you can adjust the time-per-question below so you can practice at the same pace you will need to use on the actual exam.",
  lorem_p:
    "Lorem ipsum is simply dummy text of the printing and typesetting industry. Lorem ipsum ha been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley otype and scrambled it to make a type specimen book.",
  are_you_sure: "Are you sure",
  delete_message: "Once you deleted, you will not be able to recover this !",
  warning: "warning",
  message_add: "Add message",
  message_edit: "Edit message",
  general: "General",
  lawschool: "Law schools",
  student: "Student",
  item_bank_code: "Item bank code",
  multiple_choice_question: "Multiple choice questions",
  option: "Option",
  explanation: "Explanation",
  search: "Search",
  we_are_here_to_help_you: "We're here to help you.",
  have_questions:
    "Have questions about this software? or having trouble using this software?",
  view_help: "VIEW HELP PAGE",
  students_setting: "General settings",
  stud_settings_default_date: "Default date",
  stud_settings_dafault_date_perform: "Default dates for performance stats",
  stud_settinges_today: "Today",
  stud_settings_session: "Session",
  stud_settings_custom: "Custom",
  stud_settings_timing: "Timing",
  stud_settings_reset: "Reset",
  stud_settings_stud_info: "Student information",
  stud_settings_lawschool: "Harvard law school",
  stud_settings_exams: "Exam(s)",
  stud_settings_dateinfo: "February 2020 in new york",
  stud_settings_support: "Support",
  video_lecture: "Video lectures",
  support: "Support",
  contact: "Contact",
  precreated_exam: "Pre-created exams",
  precreated_exam_code: "Exam code",
  precreated_exam_name: "Exam name",
  precreated_exam_desc: "Description",
  number_of_question_included: "# of question(s)",
  exam_information: "Exam information",
  questions_information: "Questions information",
  all: "All",
  message_sendto_all: "Everyone",
  only_lawschool: "Only law schools",
  only_student: "Only students",
  full_name: "Full name",
  all_user_stat_overview: "All user stats on overview",
  keyboard_shrtcuts: "Keyboard shortcuts",
  basic_info: "Basci information",
  preferences: "Preferences",
  rivision_history: "Rivision history",
  itembank_title: "Item bank title",
  itembank_code: "Code",
  student_info: "Please enter student information.",
  study_info: "Please enter your study information.",
  law_school_info: "Please enter your law school information.",
  profile_info: "Please enter profile information",
  tag_info: "Please enter your tag information.",
  exam_info: "Please enter exam information",
  question_info: "Please enter question information",
  user_info: "Please enter user information",
  processed: "Processed",
  not_procressed: "New",
  lawschool_enquiry: "Law school enquiry",
  thumbNailimg: "Add thumbnail",
  upload_student: "Upload student",
  law_schools: "Law schools",
  upload_file: "Please upload your file",
  profile_active_or_inactive: "Profile active",
  item_bank_status: "Status",
  profile_status: "Profile status",
  list_law_school: "LIST LAW SCHOOL",
  Progress: "Progress",
  display_name: "Display name"
};
