export const tooltipMsg = {
  alphanumeric: "It should contain alphanumeric characters only.",
  law_school_name: "It should contain character only",
  phone_no: "It should contain 10 digits valid phone number",
  law_school_email: "It should contain valid email address",
  law_school_weblink: "It should contain valid website address",
  law_school_category: "Select school category",
  law_school_address:
    "It should contain alphanumeric characters and following special characters ,.-#",
  zip_code: "Zip code should be 5 digits",
  contact_name: "It should contain characters only",
  user_name:
    "It should contain alphanumeric characters only,no special characters are allowed",
  student_code: "It should contain alphanumeric characters only.",
  student_id: "It should contain numbers only",
  student_name: "It should contain characters only.",
  email: "It should contain valid email address.",
  select_law_school: "Select your law school.",
  enter_law_school_GPA: "It should contain score.",
  enter_law_school_LAST: "It should contain score.",
  bar_exam_batch: "Select your bar exam batch.",
  enter_expected_bar_exam_state: "Select your bar exam state.",
  selecte_bar_exam_date: "Select your expected bar exam date.",
  previous_bar_exam_taken: "It should contain numbers only.",
  enter_user_password:
    "Password must contain atleast 8 characters and should include one upperCase letter, number and one special character like ,.,-,#",
  settings_user_password:
    "It should contain atleast 8 characters and should include one uppercase letter, number and one special character like .,,-,#",
  precreated_exam_code:
    "It should contain alphanumeric characters and special character like . , - #.",
  precreated_exam_name:
    "It should contain alphanumeric characters and special character like . , - #.",
  precreated_exam_desc: "It should contain alphanumeric characters and special charecters.",
  user_role: "Select the role",
  exam_duration: "Only number is allowed",
  settings_exam_duration: "It should contain numbers and maximum length 4 digit, minimum length 2 digit",
  video_title: "It should contain alphanumeric characters only.",
  video_order: "It should contain numeric number only",
  video_url:
    "It should contain alphanumeric and special characters like -,#,.,,",
  video_category: "Select a subject",
  mesg_des: "Include a content for your message.",
  lawschool_msg_des: "provide the text of your message.",
  lawschool_msg_to: "To your lawschool students.",
  msg_title: "Include a subject for your message.",
  select_status : 'Select status',
  precreated_exam_progress:"Number of students who have taken the pre-created exams (your students vs all students nation-wide)",
  law_school_setting:"Display of users' statistics in overview page",
  delete:"Delete",
  download:"Download",
  Click_for_more_details:"Click for more details",
  select_error:"Select error category",
};
