export const subjectPerformanceData = {
    labels: [
      "Aug 18",
      "Sep 18",
      "Oct 18",
      "Nov 18",
      "Dec 18",
      "Jan 19",
      "Feb 19",
      "Mar 19",
      "Apr 19",
      "May 19",
      "Jun 19",
      "Jul 19"
    ],
    datasets: [
      {
        label: "Criminal Law",
        fill: false,
        lineTension: 0.1,
        backgroundColor: "rgba(75,192,192,0.4)",
        borderColor: "rgba(75,192,192,1)",
        borderCapStyle: "butt",
        borderDash: [],
        borderWidth: 1,
        borderDashOffset: 0.0,
        borderJoinStyle: "miter",
        pointBorderColor: "rgba(75,192,192,1)",
        pointBackgroundColor: "#fff",
        pointBorderWidth: 5,
        pointHoverRadius: 2,
        pointHoverBackgroundColor: "rgba(75,192,192,1)",
        pointHoverBorderColor: "rgba(220,220,220,1)",
        pointHoverBorderWidth: 2,
        pointRadius: 1,
        pointHitRadius: 10,
        data: [0, 65, 59, 80, 81, 56, 55, 40, 30, 40, 20, 10]
      },
  
      {
        label: "Contracts",
        fill: false,
        lineTension: 0.1,
        backgroundColor: "#006EBD",
        borderCapStyle: "butt",
        borderColor: "#006EBD",
        borderDash: [],
        borderWidth: 1,
        strokeColor: "#FF5733",
        borderDashOffset: 0.0,
        borderJoinStyle: "miter",
        pointBorderColor: "#006EBD",
        pointBackgroundColor: "#fff",
        pointBorderWidth: 1,
        pointHoverRadius: 5,
        pointHoverBackgroundColor: "rgba(75,192,192,1)",
        pointHoverBorderColor: "rgba(220,220,220,1)",
        pointHoverBorderWidth: 2,
        pointRadius: 1,
        pointHitRadius: 10,
        data: [0, 10, 30, 0, 57, 12, 89, 12, 40, 20, 70, 40]
      },
      {
        label: "Torts",
        fill: false,
        lineTension: 0.1,
        backgroundColor: "#82ca9d",
        borderColor: "#82ca9d",
        borderCapStyle: "butt",
        borderDash: [],
        borderWidth: 1,
        borderDashOffset: 0.0,
        borderJoinStyle: "miter",
        pointBorderColor: "#006EBD",
        pointBackgroundColor: "#fff",
        pointBorderWidth: 5,
        pointHoverRadius: 2,
        pointHoverBackgroundColor: "rgba(75,192,192,1)",
        pointHoverBorderColor: "rgba(220,220,220,1)",
        pointHoverBorderWidth: 2,
        pointRadius: 1,
        pointHitRadius: 10,
        data: [8, 40, 38, 90, 57, 69, 100, 23, 90, 20, 30, 40]
      },
      {
        label: "Evidence",
        fill: false,
        lineTension: 0.1,
        backgroundColor: "#003300",
        borderColor: "#003300",
        borderCapStyle: "butt",
        borderDash: [],
        borderWidth: 1,
        borderDashOffset: 0.0,
        borderJoinStyle: "miter",
        pointBorderColor: "#003300",
        pointBackgroundColor: "#fff",
        pointBorderWidth: 5,
        pointHoverRadius: 2,
        pointHoverBackgroundColor: "rgba(75,192,192,1)",
        pointHoverBorderColor: "rgba(220,220,220,1)",
        pointHoverBorderWidth: 2,
        pointRadius: 1,
        pointHitRadius: 10,
        data: [90, 56, 12, 34, 56, 56, 78, 45]
      },
      {
        label: "Constitutional Law",
        fill: false,
        lineTension: 0.1,
        backgroundColor: "#ff6666",
        borderColor: "#ff6666",
        borderCapStyle: "butt",
        borderDash: [],
        borderWidth: 1,
        borderDashOffset: 0.0,
        borderJoinStyle: "miter",
        pointBorderColor: "#ff6666",
        pointBackgroundColor: "#fff",
        pointBorderWidth: 5,
        pointHoverRadius: 2,
        pointHoverBackgroundColor: "rgba(75,192,192,1)",
        pointHoverBorderColor: "rgba(220,220,220,1)",
        pointHoverBorderWidth: 2,
        pointRadius: 1,
        pointHitRadius: 10,
        data: [0, 65, 23, 21, 46, 89, 55, 40]
      },
  
      {
        label: "Real Property",
        fill: false,
        lineTension: 0.1,
        backgroundColor: "#800000",
        borderColor: "#800000",
        borderCapStyle: "butt",
        borderDash: [],
        borderWidth: 1,
        borderDashOffset: 0.0,
        borderJoinStyle: "miter",
        pointBorderColor: "rgba(75,192,192,1)",
        pointBackgroundColor: "#800000",
        pointBorderWidth: 5,
        pointHoverRadius: 2,
        pointHoverBackgroundColor: "rgba(75,192,192,1)",
        pointHoverBorderColor: "rgba(220,220,220,1)",
        pointHoverBorderWidth: 2,
        pointRadius: 1,
        pointHitRadius: 10,
        data: [0, 90, 45, 1, 81, 56, 45, 1]
      },
      {
        label: "Civil",
        fill: false,
        lineTension: 0.1,
        backgroundColor: "#0099cc",
        borderColor: "#0099cc",
        borderCapStyle: "butt",
        borderDash: [],
        borderWidth: 1,
        borderDashOffset: 0.0,
        borderJoinStyle: "miter",
        pointBorderColor: "#0099cc",
        pointBackgroundColor: "#fff",
        pointBorderWidth: 5,
        pointHoverRadius: 2,
        pointHoverBackgroundColor: "rgba(75,192,192,1)",
        pointHoverBorderColor: "rgba(220,220,220,1)",
        pointHoverBorderWidth: 2,
        pointRadius: 1,
        pointHitRadius: 10,
        data: [82, 65, 59, 30, 81, 97, 43, 50]
      }
    ]
  };